name: Verify

on:
  push:
  pull_request:

permissions: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn setup-python
      - run: yarn verify
